apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: actual-budget-claim
  name: actual-budget-claim
  namespace: actual-budget
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
